#  Horizen Secure Node docker template
#  Copyright © 2019 cryon.io
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published
#  by the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
#  Contact: cryi@tutanota.com

version: "2.4"
services:
  certbot:
    restart: "no"
    build: .
    volumes:
      - "../../data/certs:/home/certbot/certs:rw"
      - "../../data/certbot:/home/certbot/certbot:rw"
      - "./run.sh:/home/certbot/run.sh:ro"
    environment:
      - fqdn=fqdn
      - ip=ip
    cpus: '0.50'
    mem_limit: '500M'
    ports:
      - "80:8080"